# Generated by Django 4.2.4 on 2024-03-25 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='curatedlist',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='content', validators=[django.core.validators.MinLengthValidator(20)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='curated_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interaction.curatedlist'),
        ),
    ]
