# Generated by Django 4.2.4 on 2024-03-28 17:51

from django.db import migrations, models
import igdb.interaction.validators


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_rename_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedlist',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[igdb.interaction.validators.validate_title]),
        ),
    ]
