# Generated by Django 4.2.4 on 2024-03-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_alter_curatedlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='review name', max_length=100),
            preserve_default=False,
        ),
    ]
