# Generated by Django 4.2.4 on 2024-03-31 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedlist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='curated_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.curatedlist'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
