# Generated by Django 4.2.4 on 2024-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_curatedlist_slug_review_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game_name',
            field=models.CharField(default='base name', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
