# Generated by Django 4.2.4 on 2024-03-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_review_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='game_name',
        ),
    ]
