# Generated by Django 4.2.4 on 2024-03-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_remove_review_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedlist',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='fk_curated_list_list_item', to='interaction.listitem'),
        ),
    ]
