# Generated by Django 4.2.4 on 2024-03-31 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import igdb.interaction.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_alter_nonvideogame_type_alter_videogame_type'),
        ('interaction', '0008_curatedlist_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonVideoGameCuratedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[igdb.interaction.validators.validate_title])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('games', models.ManyToManyField(related_name='fk_list_nonvideogames', to='games.nonvideogame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGameCuratedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[igdb.interaction.validators.validate_title])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('games', models.ManyToManyField(related_name='fk_list_videogames', to='games.videogame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='curated_list',
        ),
        migrations.DeleteModel(
            name='CuratedList',
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
