# Generated by Django 4.2.4 on 2024-03-17 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('avatar', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interaction.comment')),
                ('curated_lists', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.curatedlist')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interaction.like')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interaction.review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
