# Generated by Django 4.2.4 on 2024-03-28 18:24

from django.db import migrations, models
import igdb.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, validators=[igdb.main.validators.validate_age]),
        ),
    ]
